require('plugins')
require('keybindings')
require('lualine-config')
require('bufferline-config')
require('options')
require('nvim-tree-config')
require('auto-pairs-config')
require('treesitter-config')
require('whichkey-config')
require('telescope-config')
require('lsp')
--vim.cmd('colorscheme nord') backup
vim.cmd('colorscheme rose-pine')
